config/routes.rb
Rails.application.routes.draw do
  resources :rugby_world_cup_host_countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rugby_world_cup_host_country.rb
class RugbyWorldCupHostCountry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rugby_world_cup_host_countries_controller.rb
class RugbyWorldCupHostCountriesController < ApplicationController
  before_action :set_rugby_world_cup_host_country, only: [:show, :edit, :update, :destroy]

  # GET /rugby_world_cup_host_countries
  # GET /rugby_world_cup_host_countries.json
  def index
    @rugby_world_cup_host_countries = RugbyWorldCupHostCountry.all
  end

  # GET /rugby_world_cup_host_countries/1
  # GET /rugby_world_cup_host_countries/1.json
  def show
  end

  # GET /rugby_world_cup_host_countries/new
  def new
    @rugby_world_cup_host_country = RugbyWorldCupHostCountry.new
  end

  # GET /rugby_world_cup_host_countries/1/edit
  def edit
  end

  # POST /rugby_world_cup_host_countries
  # POST /rugby_world_cup_host_countries.json
  def create
    @rugby_world_cup_host_country = RugbyWorldCupHostCountry.new(rugby_world_cup_host_country_params)

    respond_to do |format|
      if @rugby_world_cup_host_country.save
        format.html { redirect_to @rugby_world_cup_host_country, notice: 'Rugby world cup host country was successfully created.' }
        format.json { render :show, status: :created, location: @rugby_world_cup_host_country }
      else
        format.html { render :new }
        format.json { render json: @rugby_world_cup_host_country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rugby_world_cup_host_countries/1
  # PATCH/PUT /rugby_world_cup_host_countries/1.json
  def update
    respond_to do |format|
      if @rugby_world_cup_host_country.update(rugby_world_cup_host_country_params)
        format.html { redirect_to @rugby_world_cup_host_country, notice: 'Rugby world cup host country was successfully updated.' }
        format.json { render :show, status: :ok, location: @rugby_world_cup_host_country }
      else
        format.html { render :edit }
        format.json { render json: @rugby_world_cup_host_country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rugby_world_cup_host_countries/1
  # DELETE /rugby_world_cup_host_countries/1.json
  def destroy
    @rugby_world_cup_host_country.destroy
    respond_to do |format|
      format.html { redirect_to rugby_world_cup_host_countries_url, notice: 'Rugby world cup host country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rugby_world_cup_host_country
      @rugby_world_cup_host_country = RugbyWorldCupHostCountry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rugby_world_cup_host_country_params
      params.require(:rugby_world_cup_host_country).permit(:name, :total_attendance, :matches, :stadium_capacity, :held_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rugby_world_cup_host_countries_helper.rb
module RugbyWorldCupHostCountriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChartkickSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rugby_world_cup_host_countries/_form.html.erb
<%= form_with(model: rugby_world_cup_host_country, local: true) do |form| %>
  <% if rugby_world_cup_host_country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rugby_world_cup_host_country.errors.count, "error") %> prohibited this rugby_world_cup_host_country from being saved:</h2>

      <ul>
      <% rugby_world_cup_host_country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :total_attendance %>
    <%= form.number_field :total_attendance %>
  </div>

  <div class="field">
    <%= form.label :matches %>
    <%= form.number_field :matches %>
  </div>

  <div class="field">
    <%= form.label :stadium_capacity %>
    <%= form.number_field :stadium_capacity %>
  </div>

  <div class="field">
    <%= form.label :held_at %>
    <%= form.datetime_select :held_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rugby_world_cup_host_countries/edit.html.erb
<h1>Editing Rugby World Cup Host Country</h1>

<%= render 'form', rugby_world_cup_host_country: @rugby_world_cup_host_country %>

<%= link_to 'Show', @rugby_world_cup_host_country %> |
<%= link_to 'Back', rugby_world_cup_host_countries_path %>

app/views/rugby_world_cup_host_countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rugby World Cup Host Countries</h1>

<%= column_chart RugbyWorldCupHostCountry.pluck(:held_at, :total_attendance) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Total attendance</th>
      <th>Matches</th>
      <th>Stadium capacity</th>
      <th>Held at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rugby_world_cup_host_countries.each do |rugby_world_cup_host_country| %>
      <tr>
        <td><%= rugby_world_cup_host_country.name %></td>
        <td><%= rugby_world_cup_host_country.total_attendance %></td>
        <td><%= rugby_world_cup_host_country.matches %></td>
        <td><%= rugby_world_cup_host_country.stadium_capacity %></td>
        <td><%= rugby_world_cup_host_country.held_at %></td>
        <td><%= link_to 'Show', rugby_world_cup_host_country %></td>
        <td><%= link_to 'Edit', edit_rugby_world_cup_host_country_path(rugby_world_cup_host_country) %></td>
        <td><%= link_to 'Destroy', rugby_world_cup_host_country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rugby World Cup Host Country', new_rugby_world_cup_host_country_path %>

app/views/rugby_world_cup_host_countries/new.html.erb
<h1>New Rugby World Cup Host Country</h1>

<%= render 'form', rugby_world_cup_host_country: @rugby_world_cup_host_country %>

<%= link_to 'Back', rugby_world_cup_host_countries_path %>

app/views/rugby_world_cup_host_countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rugby_world_cup_host_country.name %>
</p>

<p>
  <strong>Total attendance:</strong>
  <%= @rugby_world_cup_host_country.total_attendance %>
</p>

<p>
  <strong>Matches:</strong>
  <%= @rugby_world_cup_host_country.matches %>
</p>

<p>
  <strong>Stadium capacity:</strong>
  <%= @rugby_world_cup_host_country.stadium_capacity %>
</p>

<p>
  <strong>Held at:</strong>
  <%= @rugby_world_cup_host_country.held_at %>
</p>

<%= link_to 'Edit', edit_rugby_world_cup_host_country_path(@rugby_world_cup_host_country) %> |
<%= link_to 'Back', rugby_world_cup_host_countries_path %>